# Generated by Django 4.1.2 on 2022-10-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('gender', models.TextField()),
                ('number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('district', models.TextField()),
                ('branches', models.TextField()),
                ('account', models.TextField()),
                ('materialsprovided', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
