# Generated by Django 4.1.2 on 2022-10-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_alter_form_dob_alter_form_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='account',
        ),
        migrations.RemoveField(
            model_name='form',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='form',
            name='district',
        ),
    ]
