# Generated by Django 4.1.2 on 2022-10-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_remove_form_account_remove_form_branches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
