# Generated by Django 4.1.2 on 2022-10-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_alter_form_dob_alter_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='address',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='dob',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='materialsprovided',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='form',
            name='number',
            field=models.IntegerField(default=True),
        ),
    ]
